apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: nimc-production
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-registry/nimc-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: nimc-config
              key: app-port
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: nimc-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: nimc-config
              key: db-port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: nimc-config
              key: db-name
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: nimc-config
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nimc-secrets
              key: db-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: nimc-secrets
              key: jwt-secret
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: nimc-config
              key: node-env
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: nimc-config
              key: frontend-url
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: nimc-production
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000